name: projek
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7 # vir svg prentjies
  intl: ^0.18.1 # om die datum functions te gebruik
  firebase_core: ^2.0.0 # om aan firebase te konnekteer
  cloud_firestore: ^4.0.0 # om te skryf na firebase se databasis
  uuid: ^4.0.0 # unieke kodes te genereer vir kennisgewing id's
  shared_preferences: ^2.0.15 # gebruik om darkmode of lighrmode te stoor

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/griffonSVG.svg
  - assets/settings.svg
  - assets/question_mark.svg
  - assets/personal_bag_question.svg
  - assets/menu_book.svg
  - assets/home.svg
  - assets/background_white.svg
  - assets/background_black.svg
  - assets/add_circle.svg
