// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMVr1-X_VA206iO7_-6kHM0j_f-XRFjm4',
    appId: '1:6023145506:web:e635cfdc197f06d77d027b',
    messagingSenderId: '6023145506',
    projectId: 'ha2-projek',
    authDomain: 'ha2-projek.firebaseapp.com',
    storageBucket: 'ha2-projek.firebasestorage.app',
    measurementId: 'G-ZKBTK62XVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC79OiwchrKrYkWng5XEsw539yEfGW8EMY',
    appId: '1:6023145506:android:923b6c83dd9ea1047d027b',
    messagingSenderId: '6023145506',
    projectId: 'ha2-projek',
    storageBucket: 'ha2-projek.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMVr1-X_VA206iO7_-6kHM0j_f-XRFjm4',
    appId: '1:6023145506:web:5ce630f2fc7e59167d027b',
    messagingSenderId: '6023145506',
    projectId: 'ha2-projek',
    authDomain: 'ha2-projek.firebaseapp.com',
    storageBucket: 'ha2-projek.firebasestorage.app',
    measurementId: 'G-1R6C5WP19R',
  );

}